name: Update SDK Mappings

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests toml
      
      - name: Update SDK mappings
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python scripts/comprehensive_branch_aware_mapper.py
      
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email gh-actions@users.noreply.github.com
          git add docs/data/sdk-mappings/
          git diff --cached --quiet || git commit -m "chore: Update SDK mappings [automated]" && git push
        continue-on-error: true  # don't fail if nothing changed
